CREATE DATABASE MODUDEAL;

USE MODUDEAL;

-- 관리자 테이블 생성
CREATE TABLE ADMIN (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO ADMIN VALUES (1, 'nsadmin' , 'kiki@@1346');

-- 사용자 테이블 생성
CREATE TABLE USER (
    USER_ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(200) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    HP VARCHAR(13) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    ADDRESS_ZIPCODE VARCHAR(10),
    ADDRESS_ROAD VARCHAR(200),
    ADDRESS_JIBUN VARCHAR(200),
    ADDRESS_NAMUJI VARCHAR(200),
    ACTIVE_YN CHAR(1) DEFAULT 'y',
    INACTIVE_AT DATE,
    JOIN_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 제품 테이블 생성
CREATE TABLE PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    QTY INT,
    PRICE INT,
    PRODUCT_CATEGORY VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50),
    PRODUCT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- 제품 이미지 테이블 생성
CREATE TABLE PRODUCT_IMG (
    IMG_UUID CHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    IMG_ORIGINAL_NAME VARCHAR(255) NOT NULL,
    IMG_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 채팅 테이블 생성
CREATE TABLE CHAT (
    CHAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID VARCHAR(50) NOT NULL,
    RECEIVER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    MESSAGE TEXT NOT NULL,
    SEND_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 장바구니 테이블 생성
CREATE TABLE CART (
    CART_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QTY INT NOT NULL,
    PRICE INT NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TITLE VARCHAR(255) NOT NULL,
    IMG_UUID CHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 공지사항 테이블 생성
CREATE TABLE NOTICE (
    NOTICE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

-- 리뷰 테이블 생성
CREATE TABLE REVIEW (
    REVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    REVIEW TEXT NOT NULL,
    REVIEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 제품 좋아요 테이블 생성
CREATE TABLE PRODUCT_LIKE (
    PRODUCT_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (PRODUCT_ID, USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- 채팅 활성화 테이블 생성
CREATE TABLE CHAT_ACTIVATION (
    CHAT_ACTIVATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CHAT_ID INT NOT NULL,
    RECEIVER_ID VARCHAR(50) NOT NULL,
    SENDER_ID VARCHAR(50) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'y',
    ACTIVATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID)
);